//! Generate a commented `.env` template from a [`clap::Command`].
//!
//! See <https://github.com/clap-rs/clap/issues/4729>.

use std::fmt::Write as _;

use clap::{ArgAction, Command};

/// Render a deterministic `.env` template for every argument that declares an `env` binding.
pub fn generate_dotenv(cmd: &Command) -> String {
    let mut out = String::from("# Generated by clap_dotenv\n#\n");
    write_command(cmd, &mut out);
    out
}

fn write_command(cmd: &Command, out: &mut String) {
    let mut args: Vec<_> = cmd.get_arguments().collect();
    args.sort_by_key(|a| a.get_env().map(|e| e.to_string_lossy().into_owned()));

    for arg in args {
        let Some(env) = arg.get_env() else {
            continue;
        };
        let env = env.to_string_lossy();

        if let Some(help) = arg.get_help() {
            let _ = writeln!(out, "# {help}");
        } else if let Some(long) = arg.get_long_help() {
            // First line of long help as a short comment.
            let line = long.to_string();
            let first = line.lines().next().unwrap_or("").trim();
            if !first.is_empty() {
                let _ = writeln!(out, "# {first}");
            }
        }

        let possible: Vec<&str> = arg
            .get_possible_values()
            .iter()
            .map(|v| v.get_name())
            .collect();
        if !possible.is_empty() {
            let _ = writeln!(out, "# Possible values: {}", possible.join(", "));
        }

        let type_hint = type_hint(arg.action());
        let _ = writeln!(out, "# Type: {type_hint}");

        match arg.get_default_values() {
            defaults if !defaults.is_empty() => {
                let joined = defaults
                    .iter()
                    .map(|v| v.to_string_lossy())
                    .collect::<Vec<_>>()
                    .join(",");
                let _ = writeln!(out, "# {env}={joined}");
            }
            _ => {
                let _ = writeln!(out, "# {env}=");
            }
        }
        out.push('\n');
    }

    for sub in cmd.get_subcommands() {
        write_command(sub, out);
    }
}

fn type_hint(action: &ArgAction) -> &'static str {
    match action {
        ArgAction::SetTrue | ArgAction::SetFalse | ArgAction::Count => "bool (true/false / 1/0)",
        ArgAction::Append => "list (comma-separated or repeated)",
        _ => "string",
    }
}

#[cfg(test)]
mod tests {
    use clap::{Arg, ArgAction, Command};

    use super::generate_dotenv;

    #[test]
    fn renders_env_args_with_help_and_defaults() {
        let cmd = Command::new("demo")
            .arg(
                Arg::new("port")
                    .long("port")
                    .env("APP_PORT")
                    .help("HTTP listen port")
                    .default_value("8080"),
            )
            .arg(
                Arg::new("verbose")
                    .long("verbose")
                    .env("APP_VERBOSE")
                    .action(ArgAction::SetTrue)
                    .help("Enable verbose logging"),
            )
            .arg(Arg::new("ignored").long("ignored").help("no env"));

        let out = generate_dotenv(&cmd);
        assert!(out.contains("# HTTP listen port"));
        assert!(out.contains("# APP_PORT=8080"));
        assert!(out.contains("# Enable verbose logging"));
        assert!(out.contains("# Type: bool (true/false / 1/0)"));
        assert!(out.contains("# APP_VERBOSE="));
        assert!(!out.contains("ignored"));
    }
}
